.TH "src/include/config.hpp" 3 "Tue Mar 5 2024 12:58:03" "Version 0.1.3" "jsonToBatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/config.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAJOR_VERSION\fP   0"
.br
.ti -1c
.RI "#define \fBMINOR_VERSION\fP   1"
.br
.ti -1c
.RI "#define \fBPATCH_VERSION\fP   3"
.br
.ti -1c
.RI "#define \fBDESCRIPTION\fP   'A simple tool to convert json to batch'"
.br
.ti -1c
.RI "#define \fBPROJECT_NAME\fP   'jsonToBatch'"
.br
.ti -1c
.RI "#define \fBAUTHORS\fP   'Elena Schwarzbach, Max Rodler, Simon Blum, Sonia Sinaci'"
.br
.ti -1c
.RI "#define \fBHOMEPAGE_URL\fP   'https://definitelynotsimon13\&.github\&.io/ProjectJsonToBat'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AUTHORS   'Elena Schwarzbach, Max Rodler, Simon Blum, Sonia Sinaci'"

.PP
Definition at line \fB9\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define DESCRIPTION   'A simple tool to convert json to batch'"

.PP
Definition at line \fB7\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define HOMEPAGE_URL   'https://definitelynotsimon13\&.github\&.io/ProjectJsonToBat'"

.PP
Definition at line \fB10\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define MAJOR_VERSION   0"

.PP
Definition at line \fB4\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define MINOR_VERSION   1"

.PP
Definition at line \fB5\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define PATCH_VERSION   3"

.PP
Definition at line \fB6\fP of file \fBconfig\&.hpp\fP\&.
.SS "#define PROJECT_NAME   'jsonToBatch'"

.PP
Definition at line \fB8\fP of file \fBconfig\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatch from the source code\&.
