.TH "src/main.cpp" 3 "Fri Mar 1 2024 11:04:33" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <jsoncpp/json\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line \fB4\fP of file \fBmain\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
