.TH "src/nurTest.cpp" 3 "Fri Mar 1 2024 13:32:14" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/nurTest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <jsoncpp/json/json\&.h>\fP
.br
\fC#include <jsoncpp/json/value\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line \fB10\fP of file \fBnurTest\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
