.TH "todo" 3 "Tue Mar 5 2024 12:58:03" "Version 0.1.3" "jsonToBatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.PP

.IP "\fBpage \fBMain Page\fP \fP" 1c
.IP "\(bu" 2

.PP
.PP
.IP "\fBMember \fBWIP::setupEasyLogging\fP ()\fP" 1c
.IP "\(bu" 2
Should be moved to a separate file
.IP "\(bu" 2
Proper configuration of easylogging++ 
.PP
.PP

