.TH "WIP" 3 "Tue Mar 5 2024 08:14:17" "Version 0.1.1" "jsonToBatch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WIP
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetupEasyLogging\fP ()"
.br
.RI "Setup the easylogging++ logger\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void WIP::setupEasyLogging ()"

.PP
Setup the easylogging++ logger\&. 
.PP
\fBTodo\fP
.RS 4

.IP "\(bu" 2
Should be moved to a separate file
.IP "\(bu" 2
Proper configuration of easylogging++ 
.PP
.RE
.PP

.PP
Definition at line \fB75\fP of file \fBmain\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatch from the source code\&.
